Added error logging to a file
MarkusReynolds1989/BugTracker pull request #20
Opened 2022-08-21 08:10 UTC by aseemsahoo

Resolved #19 
- Now, you can easily check the log file for updates.
- The logging directory is as follows;
` rootdirectory / logs / {year} / {year}-{month} / Error-logs-{date}.txt `
- Year, month & date parameters in {    } are written dynamically by the logger.

2022-08-21 11:16 UTC, MarkusReynolds1989 commented
I had a few suggestions, really appreciate your help!

2022-08-21 18:47 UTC, MarkusReynolds1989 requested changes

2022-08-21 18:47 UTC, MarkusReynolds1989 commented on src/BugTrackerMain/Logging/Logger.cs
> +namespace BugTracker.Logging
Can you use file level namespaces instead?

2022-08-21 18:47 UTC, MarkusReynolds1989 commented on src/BugTrackerMain/Logging/Logger.cs
> +                if (!File.Exists(errorFile))
Would you please make these writes asynchronous and wrap them in a try catch? We might also want to throw a mutex on the file in case we are doing multiple writes at a time (each would wait until the mutex is unblocked).

2022-08-21 18:47 UTC, MarkusReynolds1989 commented on src/BugTrackerMain/Logging/Logger.cs
> +    public class Logger
Can we use the ILogger interface?
https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.logging.ilogger?view=dotnet-plat-ext-6.0

2022-08-21 19:46 UTC, aseemsahoo commented on src/BugTrackerMain/Logging/Logger.cs
> +namespace BugTracker.Logging
Yep, I'll change this.

2022-08-22 00:29 UTC, MarkusReynolds1989 commented on src/BugTrackerMain/Logging/Logger.cs
> +namespace BugTracker.Logging
Thanks

2022-08-22 09:25 UTC, aseemsahoo commented on src/BugTrackerMain/Logging/Logger.cs
> +                if (!File.Exists(errorFile))
Yeah, I'll look into it.

2023-07-11 15:20 UTC, closed without merging